name: Send Daily Word Reminder

on:
  schedule:
    # Runs at 4:30 AM UTC -> 10:00 AM IST every day
    - cron: '30 4 * * *'
  workflow_dispatch: # for manual testing

jobs:
  send_reminder_email:
    runs-on: ubuntu-latest
    name: Email Reminder Job
    steps:
      - name: Send reminder email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          # Use GitHub Secrets to store sensitive information
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: "What is today's Word of the Day?"

          body: |
            Hello!
            
            It's time to update the Word of the Day.
            
            1. If you haven't played today, here is the link:
              https://www.nytimes.com/games/wordle/index.html

            2. Need some assistance? Use the Word Finder:
              https://raghav-awasty.github.io/wordle-word-finder/index.html
            
            3. Once you have the word, enter it here:
              https://raghav-awasty.github.io/wordle-word-finder/src/submit.html
            
            Thanks!

          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions Reminder <${{ secrets.MAIL_USERNAME }}>